repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Verifica la versión actual
    hooks:
      - id: trailing-whitespace  # Eliminar espacios en blanco al final de cada línea
      - id: end-of-file-fixer  # Asegura una nueva línea al final de los archivos
      - id: check-yaml  # Valida archivos YAML

  - repo: https://github.com/psf/black
    rev: 23.1a1  # Verifica la versión actual
    hooks:
      - id: black  # Formateo automático del código Python

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Usa la versión más reciente
    hooks:
      - id: flake8
        args: [ "--max-line-length=88", "--ignore=E501" ]  # Personalización de flake8
